kind: ConfigMap
apiVersion: v1
metadata:
  name: springappconfigmap
  namespace: test-ns
data:
  username: springapp
  password: mongodb@123

---
apiVersion: v1
kind: Secret
metadata:
  name: springappsecrets
  namespace: test-ns
type: Opaque
stringData:   # We can define multiple key value pairs.
  password: devdb@123
